name: Build and test code

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:


jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.19.x
      - name: Check out code
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
      - name: Verify
        run: go mod verify
      - name: Test
        run: go test -v ./...